# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'ExampleDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleDemo

  target 'ExampleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'JSONModel'
pod 'AFNetworking', '~> 3.0'

end
